### ISSUE TITLE
 throwIfFatal detected a jvm fatal exception, which is thrown and logged below: java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by rushmi0** [ACINQ/secp256k1-kmp#109]
I'm not sure that's the problem.  Is this lib?  or set it in the file  config is not wrong

 found issue with using `fr.acinq.secp256k1.Secp256k1` (this issue does not occur for JVM)

when compiled the Kotlin code into native libraries using GraalVM CE 21.0.2+13.1.

When I tested the application, I encountered this problem:
```
reactor.core.Exceptions - throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.ExceptionInInitializerError: null
        at fr.acinq.secp256k1.Secp256k1.<clinit>(Secp256k1.kt)
        ...
Caused by: java.lang.IllegalStateException: Could not load native Secp256k1 JNI library. Have you added the JNI dependency?
	at fr.acinq.secp256k1.Secp256k1JvmKt.getSecpk256k1(Secp256k1Jvm.kt:35)
	at fr.acinq.secp256k1.Secp256k1$Companion.<init>(Secp256k1.kt:259)
	at fr.acinq.secp256k1.Secp256k1$Companion.<clinit>(Secp256k1.kt)
	... 56 common frames omitted

```
Is there a solution to this problem?

**Comment by rushmi0** [comment]
![swappy-20240615-134613](https://github.com/ACINQ/secp256k1-kmp/assets/120770468/19632485-9c65-4a03-b0e8-9ca30436ca76)

**Comment by rushmi0** [comment]
![image](https://github.com/ACINQ/secp256k1-kmp/assets/120770468/589a8ac0-4582-43e8-a085-82c2ce672d3d)

**Comment by rushmi0** [comment]
https://github.com/rushmi0/lnwza007.git

**Comment by sstone** [comment]
The JVM code tries to extract and load JNI bindings for secp256k1, which will fail if you compile it with GraalVM (because it will fail to extract the JNI library embedded in the JAR).
Using GraalVM here is the wrong approach: the whole point of Kotlin Multi Platform is to create native executables/libraries as well as JVM libraries. If that is what you want, then simply create a KMP project and use the right dependencies for your target OS (we support linux, ios, macos). This is what we do in our KMP projects (https://github.com/ACINQ/phoenixd, https://github.com/ACINQ/bitcoin-kmp,...)
