### ISSUE TITLE
Functions for parsing signatures are not exported

### ISSUE THREAD

**Issue by jirijakes** [ACINQ/secp256k1-kmp#111]
I would like to use `secp256k1_ecdsa_signature_parse_compact` and `secp256k1_ecdsa_signature_parse_der` as a means to validate signatures. Unfortunately these functions are currently not exposed.

Would it be possible to export them? I can attempt to do so, if there are no obstacles in having them in the library.

**Comment by sstone** [comment]
We've chosen to use byte arrays instead of specific classes for signature, private keys, public keys... to keep the interface simple, which is why we don't export `secp256k1_ecdsa_signature_parse_compact` and `secp256k1_ecdsa_signature_parse_der` (which are used to convert byte arrays to internal secp256k1 structures).

When you use a signature, that cannot be parsed, `secp256k1-kmp` will throw an exception with a specific error message, Is that enough for your use case ?

**Comment by jirijakes** [comment]
Thanks for the response.

> When you use a signature, that cannot be parsed, secp256k1-kmp will throw an exception with a specific error message, Is that enough for your use case ?

It's not ideal as I would like to perform validation of the signature before I start using it (to avoid repetitive error handling) but I understand that it is not in line with the way the library was designed.

Therefore let me close the issue and thanks a lot for the explanation.
